id: P006763
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:39.472385
source_metadata:
  id: bdr:W8LS19894
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ།
  author: ''
  volumes:
    6e7c01b1f11a478ea50a5fa56d436757:
      image_group_id: I8LS19896
      title: ''
      volume_number: 1
      total_pages: 974
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
