id: IF19D9977
legacy_id: P006763
ocr_import_info:
  bdrc_scan_id: W8LS19894
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:33:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:36:00.124171+00:00'
last_modified: 2022-09-04 12:36:37.302673
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS19894
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS19894
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.6603575456750963
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I8LS19896:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS19896
      total_pages: 974
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS19896.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6603575456750963
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
