id: IF19D9977
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:35:51+00:00'
last_modified: '2022-06-08T06:41:21.845989+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19894
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5C4D:
      image_group_id: I8LS19896
      title: ''
      total_pages: 974
      order: 1
      base_file: 5C4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
